# Generated by Django 4.1.7 on 2023-04-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0007_invitationcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 13, 19, 48, 955803, tzinfo=datetime.timezone.utc)),
        ),
    ]
