# Generated by Django 4.1.7 on 2023-04-24 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0010_alter_invitationcodes_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcodes',
            name='realeased_date',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 15, 3, 8, 139029, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='apomFlJk5evMslz', max_length=15),
        ),
    ]
