# Generated by Django 4.1.7 on 2023-04-26 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0016_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 3, 13, 59, 26, 21693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='YqNo9Fgn52yU8VV', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='priceProduct',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
