# Generated by Django 4.1.7 on 2023-05-22 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0019_rename_registro_user_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationcodes',
            name='is_used',
        ),
        migrations.AddField(
            model_name='invitationcodes',
            name='countUsers',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 29, 15, 20, 6, 189638, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='g9cmViFeGmVG7NK', max_length=15, unique=True),
        ),
    ]
