# Generated by Django 4.1.7 on 2023-05-25 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0022_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='countUsers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 1, 18, 44, 25, 727421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='FDE8LS6vs8RXEnm', max_length=15),
        ),
    ]
