# Generated by Django 4.1.7 on 2023-05-27 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0029_product_aditional_details_product_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variants',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 3, 19, 53, 53, 89575, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='ANMAH4aAUkNtKRO', max_length=15),
        ),
    ]
