# Generated by Django 4.1.7 on 2023-06-09 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0034_remove_transacts_product_productdigit_datecreated_pd_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdigit',
            old_name='dateCreated_PD',
            new_name='dateCreated',
        ),
        migrations.RenameField(
            model_name='productdigit',
            old_name='name_PD',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='productdigit',
            old_name='price_PD',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='productdigit',
            old_name='quantity_PD',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='productdigit',
            old_name='subCategory_PD',
            new_name='subCategory',
        ),
        migrations.RenameField(
            model_name='productdigit',
            old_name='text_preview_PD',
            new_name='text_preview',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 14, 22, 37, 194377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='rTalGlJegMICKmC', max_length=15),
        ),
    ]
