# Generated by Django 4.1.7 on 2023-06-09 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0035_rename_datecreated_pd_productdigit_datecreated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 14, 31, 9, 773622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='tw9FUJtJdFnrPfx', max_length=15),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
