# Generated by Django 4.1.7 on 2023-06-09 16:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0036_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 16, 16, 24, 29, 814871, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='Vmxg8fItIBAsDIP', max_length=15),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
