# Generated by Django 4.2 on 2023-06-13 04:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0041_rename_name_stores_namestore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdigit',
            old_name='name',
            new_name='nameStore',
        ),
        migrations.RenameField(
            model_name='stores',
            old_name='nameStore',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 4, 21, 55, 709111, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='Mi5vWuZWBXe6vIe', max_length=15),
        ),
    ]
