# Generated by Django 4.2 on 2023-06-18 21:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0052_rename_namemethod_methodproducts_nameproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 21, 58, 4, 462953, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='yJ6jND3zrMIjYDT', max_length=15),
        ),
    ]
