# Generated by Django 4.2 on 2023-06-18 22:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0054_methodproducts_actquantity_methodproducts_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodproducts',
            name='sendDirection',
            field=models.CharField(default='C: 97 /324234', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 22, 1, 4, 36622, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='7DMsaBsEl0Twg9g', max_length=15),
        ),
    ]
