# Generated by Django 4.2 on 2023-06-19 02:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0055_methodproducts_senddirection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 26, 2, 15, 28, 800927, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='wD1gszRcwekh7NN', max_length=15),
        ),
        migrations.AlterField(
            model_name='methodproducts',
            name='sendDirection',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='sendDirection',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
