# Generated by Django 4.1.7 on 2023-06-21 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0057_user_direction_user_phonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdigit',
            name='additional_details',
            field=models.CharField(default='Description de la vida, lorem ipsum y no se que sigue despues de eso, no se porque me meti en desarrollo frontend si soy backend', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productdigit',
            name='description',
            field=models.CharField(default='Tampoco se de frameworks de frontend, solo estoy aprendiendo para sobrevivir y estar tranquilo en mi casa mientras avanzo en un proyecto a dos horas por dia', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 28, 15, 23, 41, 893618, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='tbfKIMqWckdJFHF', max_length=15),
        ),
    ]
