# Generated by Django 4.1.7 on 2023-06-22 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0060_checkersolic_name_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkersolic',
            name='name',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 19, 13, 55, 701693, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='hwMLuCNDmd07aqO', max_length=15),
        ),
    ]
