# Generated by Django 4.1.7 on 2023-06-22 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0061_remove_checkersolic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdigit',
            name='needChecker',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 29, 19, 57, 12, 264960, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='n241GFHgXHBpRgm', max_length=15),
        ),
    ]
