# Generated by Django 4.1.7 on 2023-06-23 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0065_checkersolic_datecreated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdigit',
            name='comisionCheck',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 30, 18, 31, 47, 84171, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='LnSzK9p8T72Hl6p', max_length=15),
        ),
    ]
