# Generated by Django 4.1.7 on 2023-06-28 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0070_subcategory_usercreator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacts',
            name='status',
            field=models.CharField(choices=[('Entregado', 'Entregado'), ('Procesando', 'Procesando'), ('Aceptado', 'Aceptado'), ('Rechazado', 'Rechazado')], default='Procesando', max_length=50),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 5, 19, 12, 14, 535845, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='kBtEA0ENmg6Cq08', max_length=15),
        ),
    ]
