# Generated by Django 4.1.7 on 2023-06-29 18:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0071_transacts_status_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 18, 48, 13, 512294, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='wWFbtYO7cTH4P7x', max_length=15),
        ),
        migrations.CreateModel(
            name='ReportTransacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rMessage', models.CharField(max_length=400)),
                ('dateReport', models.DateTimeField(auto_now_add=True)),
                ('transact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.transacts')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
