# Generated by Django 4.1.7 on 2023-06-29 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0072_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttransacts',
            name='noReporte',
            field=models.CharField(default='12345', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reporttransacts',
            name='status',
            field=models.CharField(choices=[('En proceso', 'En proceso'), ('Resuelto', 'Resuelto'), ('Rechazado', 'Rechazado')], default='En proceso', max_length=10),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 6, 19, 29, 5, 144377, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='vlCI9BfTYJQj7l6', max_length=15),
        ),
    ]
