# Generated by Django 4.1.7 on 2023-07-06 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0078_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 13, 15, 29, 57, 573955, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='eaKlV3dCbwCU32Y', max_length=15),
        ),
        migrations.AlterField(
            model_name='withdrawals',
            name='fecha_review',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
