# Generated by Django 4.1.7 on 2023-07-08 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0080_productdigit_checkertext_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 19, 21, 9, 910089, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='I1pmkUJcad49Mvr', max_length=15),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='additional_details',
            field=models.CharField(max_length=800),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='description',
            field=models.CharField(max_length=800),
        ),
    ]
