# Generated by Django 4.1.7 on 2023-07-08 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0081_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 19, 25, 34, 491227, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='kS5u23bFRl4ROY8', max_length=15),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='comisionCheck',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
    ]
