# Generated by Django 4.1.7 on 2023-08-02 20:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0085_rename_nameproduct_methodproducts_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfisic',
            old_name='priceProduct',
            new_name='price',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 25, 29, 731585, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='sAhXB2aovEMXDnD', max_length=15),
        ),
    ]
