# Generated by Django 4.2.4 on 2023-08-04 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0090_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 19, 51, 21, 368577, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='49xUC2Xtd6KQoWV', max_length=15),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='checkerText',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='no_solicitud',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
