# Generated by Django 4.2.3 on 2023-08-09 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0092_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdigit',
            old_name='additional_details',
            new_name='aditional_details',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 16, 19, 13, 53, 627155, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='pEjXNof74TT1UBX', max_length=15),
        ),
    ]
