# Generated by Django 4.2.3 on 2023-08-24 20:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0095_rename_image_product_productfisic_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfisic',
            name='seller',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 20, 44, 40, 813824, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='SDkHtuQxAt9ltrf', max_length=15),
        ),
        migrations.AlterField(
            model_name='productfisic',
            name='actQuantity',
            field=models.IntegerField(),
        ),
    ]
