# Generated by Django 4.1.7 on 2023-04-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_product_seller_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sellers',
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=False),
        ),
    ]
