# Generated by Django 4.1.7 on 2023-04-17 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0005_delete_sellers_product_is_digital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacts',
            name='buyers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Buyers',
        ),
    ]
