# Generated by Django 4.1.7 on 2023-04-24 13:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_alter_transacts_buyers_delete_buyers'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitationCodes', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=50)),
                ('is_used', models.BooleanField(default=False)),
                ('is_expired', models.BooleanField(default=False)),
                ('realeased_date', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2023, 5, 1, 13, 19, 0, 905147, tzinfo=datetime.timezone.utc))),
            ],
        ),
    ]
