# Generated by Django 4.1.7 on 2023-04-24 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0012_invitationcodes_realeased_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitationcodes',
            old_name='realeased_date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 1, 15, 10, 14, 433065, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='oLLkMcxkT0dyWbs', max_length=15),
        ),
    ]
