# Generated by Django 4.1.7 on 2023-05-23 13:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0020_remove_invitationcodes_is_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcodes',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 13, 3, 17, 214713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='HaOzNc0612XD9CV', max_length=15, unique=True),
        ),
    ]
