# Generated by Django 4.1.7 on 2023-05-26 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0025_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='maxPriceBTC',
            field=models.DecimalField(decimal_places=2, default=3333, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategory',
            name='minPriceBTC',
            field=models.DecimalField(decimal_places=2, default=2222, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 2, 20, 37, 47, 979569, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='W11N6V79iGPG92p', max_length=15),
        ),
    ]
