# Generated by Django 4.1.7 on 2023-06-12 15:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0039_productfisic_store_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdigit',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Api.stores'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 15, 1, 44, 602545, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='B4Oy3tEPTU6Mu1x', max_length=15),
        ),
    ]
