# Generated by Django 4.1.7 on 2023-06-12 15:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0040_productdigit_store_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stores',
            old_name='name',
            new_name='nameStore',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 19, 15, 40, 20, 315091, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='KOMiJ5xveNED8TU', max_length=15),
        ),
    ]
