# Generated by Django 4.1.7 on 2023-06-13 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0041_rename_name_stores_namestore_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdigit',
            old_name='quantity',
            new_name='actQuantity',
        ),
        migrations.AddField(
            model_name='productdigit',
            name='orgQuantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 21, 0, 41, 738024, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='XxGaDRGAApsekS3', max_length=15),
        ),
    ]
