# Generated by Django 4.2 on 2023-06-13 22:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0042_rename_quantity_productdigit_actquantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 20, 22, 52, 16, 895917, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='qZ1h9eYQLaaNvPA', max_length=15),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='productDigit',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.productdigit'),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='productFisic',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.productfisic'),
        ),
    ]
