# Generated by Django 4.1.7 on 2023-06-15 16:09

import Api.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0044_transacts_quantity_asked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 22, 16, 9, 36, 172212, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='c1pY3JktnNkHVfY', max_length=15),
        ),
        migrations.AlterField(
            model_name='productfisic',
            name='image_product',
            field=models.ImageField(default=None, upload_to=Api.models.generate_file_path),
        ),
        migrations.CreateModel(
            name='MethodProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMethod', models.CharField(max_length=50)),
                ('dateCreated', models.DateField()),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(upload_to=Api.models.generate_file_path)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Api.stores')),
            ],
        ),
        migrations.AddField(
            model_name='transacts',
            name='methodProduct',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Api.methodproducts'),
        ),
    ]
