# Generated by Django 4.1.7 on 2023-06-17 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0047_productfisic_dislikes_productfisic_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfisic',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='productfisic',
            name='likes',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 24, 20, 35, 18, 831420, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='zZdplDPsT6lFiHA', max_length=15),
        ),
    ]
