# Generated by Django 4.2 on 2023-06-18 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0048_remove_productfisic_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='userBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 14, 52, 19, 871201, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='XiJ9Rw61amt3trJ', max_length=15),
        ),
    ]
