# Generated by Django 4.2 on 2023-06-18 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0049_user_userbalance_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacts',
            name='sendDirection',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 2, 53, 913363, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='sqevjzzctIXI7lK', max_length=15),
        ),
    ]
