# Generated by Django 4.2 on 2023-06-18 17:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0050_transacts_senddirection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfisic',
            name='actQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 17, 34, 38, 621235, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='AlMVz4ug1oEmIjk', max_length=15),
        ),
    ]
