# Generated by Django 4.2 on 2023-06-18 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0051_productfisic_actquantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='methodproducts',
            old_name='nameMethod',
            new_name='nameProduct',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 21, 24, 56, 506621, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='C0TFnNRqQrIOb2Z', max_length=15),
        ),
    ]
