# Generated by Django 4.2 on 2023-06-18 21:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0053_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='methodproducts',
            name='actQuantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='methodproducts',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 25, 21, 59, 18, 263850, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='7yUWBK9kdtRPxgt', max_length=15),
        ),
    ]
