# Generated by Django 4.2 on 2023-06-25 16:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0067_productdigit_no_solicitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='priceSubCategory',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 16, 52, 17, 88718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='L4Z9yECeD7preOZ', max_length=15),
        ),
    ]
