# Generated by Django 4.1.7 on 2023-08-02 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0082_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfisic',
            old_name='dateReleased',
            new_name='dateCreated',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 19, 58, 2, 106656, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='1CJcQHKnxjUK36q', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='userBalance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=50),
        ),
    ]
