# Generated by Django 4.1.7 on 2023-08-02 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0083_rename_datereleased_productfisic_datecreated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfisic',
            old_name='nameProduct',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 9, 20, 15, 11, 631790, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='QKiHX26ixiY3DBk', max_length=15),
        ),
    ]
