# Generated by Django 4.2.4 on 2023-08-04 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0086_rename_priceproduct_productfisic_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 16, 23, 3, 152525, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='Iwhm1ePJZGKBydJ', max_length=15),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='maxPriceBTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='minPriceBTC',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
