# Generated by Django 4.2.4 on 2023-08-04 16:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0087_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfisic',
            name='variants',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 16, 37, 35, 301421, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='9HkHY9gDswLmz6p', max_length=15),
        ),
    ]
