# Generated by Django 4.2.4 on 2023-08-04 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0088_remove_productfisic_variants_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdigit',
            name='actQuantity',
        ),
        migrations.RemoveField(
            model_name='productdigit',
            name='orgQuantity',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 11, 18, 13, 17, 448308, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='ka0QRuueOWg5Y9u', max_length=15),
        ),
    ]
