# Generated by Django 4.2.3 on 2023-08-24 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0093_rename_additional_details_productdigit_aditional_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 19, 51, 51, 292382, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='bJp1kGAv5PlV00m', max_length=15),
        ),
        migrations.AlterField(
            model_name='methodproducts',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='company',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='noSeguimiento',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
