# Generated by Django 4.2.3 on 2023-08-24 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0094_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productfisic',
            old_name='image_product',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 31, 20, 11, 36, 549608, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='hZUJd0PH7FpkjbS', max_length=15),
        ),
    ]
