# Generated by Django 4.2.3 on 2023-08-26 19:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0098_gendata_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacts',
            name='total',
            field=models.DecimalField(decimal_places=2, default=12, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 2, 19, 29, 7, 180447, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='qj45yqrepeFY2VQ', max_length=15),
        ),
    ]
