# Generated by Django 4.2.3 on 2023-09-01 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0099_transacts_total_alter_invitationcodes_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gendata',
            name='price_checker',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 8, 19, 51, 50, 382359, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='invitationcodes',
            name='invitationCodes',
            field=models.CharField(default='znOQ8ApnVdDM1Z1', max_length=15),
        ),
        migrations.AlterField(
            model_name='productdigit',
            name='comisionCheck',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
